type Family = "apps" | "community" | "data" | "graphics" | "systems" | "web";

const FAMILY_TAGS: Record<Family, string[]> = {
  systems: [
    "alacritty",
    "assembly",
    "asm",
    "bash",
    "batchfile",
    "ci",
    "devops",
    "docker",
    "dockerfile",
    "github-actions",
    "makefile",
    "nix",
    "perl",
    "zig",
    "c",
    "c++",
    "cli",
    "concurrency",
    "cpp",
    "dotfiles",
    "embedded",
    "fish",
    "go",
    "golang",
    "kernel",
    "linux",
    "low-level",
    "multithreading",
    "neovim",
    "rust",
    "shell",
    "systems",
    "terminal",
    "tmux",
    "unix",
    "vim",
    "zsh",
  ],
  web: [
    "api",
    "astro",
    "django",
    "elixir",
    "mapbox",
    "markdown",
    "php",
    "ruby",
    "sass",
    "browser-extension",
    "chrome",
    "css",
    "electron",
    "express",
    "front-end",
    "frontend",
    "graphql",
    "html",
    "http",
    "javascript",
    "mapbox",
    "next",
    "next.js",
    "nextjs",
    "node",
    "node.js",
    "react",
    "rest",
    "seo",
    "svelte",
    "sveltekit",
    "tailwind",
    "tailwindcss",
    "three.js",
    "typescript",
    "ui",
    "ux",
    "vue",
    "wasm",
    "web",
    "webgl",
  ],
  data: [
    "algorithms",
    "competitive-programming",
    "galois",
    "haskell",
    "jupyter notebook",
    "mongodb",
    "mysql",
    "ocaml",
    "postgres",
    "scala",
    "tex",
    "weather",
    "wip",
    "data-science",
    "data-structures",
    "database",
    "datascience",
    "econometrics",
    "finance",
    "financial",
    "julia",
    "jupyter",
    "latex",
    "leetcode",
    "machine-learning",
    "math",
    "mathematics",
    "matplotlib",
    "ml",
    "notebook",
    "numpy",
    "orderbook",
    "pandas",
    "pdf",
    "physics",
    "plotting",
    "problem-solving",
    "python",
    "quant",
    "r",
    "research",
    "scipy",
    "simulation",
    "sql",
    "sqlite",
    "statistics",
    "stats",
    "trading",
    "typst",
    "visualization",
  ],
  apps: [
    ".net",
    "android",
    "c#",
    "objective-c",
    "csharp",
    "desktop",
    "dotnet",
    "gui",
    "ios",
    "java",
    "javafx",
    "kotlin",
    "maven",
    "gradle",
    "qt",
    "swift",
    "swing",
    "tauri",
    "windows",
    "wpf",
  ],
  graphics: [
    "2d",
    "3d",
    "animation",
    "bevy",
    "game",
    "gamedev",
    "glsl",
    "godot",
    "graphics",
    "hlsl",
    "lua",
    "opengl",
    "procedural",
    "puzzle",
    "pygame",
    "shader",
    "tower-defence",
    "tower-defense",
    "unity",
  ],
  community: [
    "club",
    "club-site",
    "community",
    "demo day",
    "event",
    "grading",
    "gdsc",
    "geauxhack",
    "group-project",
    "hackathon",
    "judging",
    "mentoring",
    "open-source",
    "sasel",
    "teaching",
    "travel",
    "volunteering",
    "workshop",
  ],
};

const FAMILY_TINT: Record<Family, string> = {
  systems: "border-mocha-blue/30 bg-mocha-blue/10 text-mocha-blue",
  web: "border-mocha-teal/30 bg-mocha-teal/10 text-mocha-teal",
  data: "border-mocha-mauve/30 bg-mocha-mauve/10 text-mocha-mauve",
  apps: "border-mocha-peach/30 bg-mocha-peach/10 text-mocha-peach",
  graphics: "border-mocha-green/30 bg-mocha-green/10 text-mocha-green",
  community: "border-mocha-yellow/30 bg-mocha-yellow/10 text-mocha-yellow",
};

const FAMILY_BAR: Record<Family, string> = {
  systems: "bg-mocha-blue",
  web: "bg-mocha-teal",
  data: "bg-mocha-mauve",
  apps: "bg-mocha-peach",
  graphics: "bg-mocha-green",
  community: "bg-mocha-yellow",
};

const FAMILIES = Object.keys(FAMILY_TINT) as Family[];

const TAG_FAMILY = new Map<string, Family>();
for (const family of FAMILIES) {
  for (const tag of FAMILY_TAGS[family]) {
    TAG_FAMILY.set(tag, family);
  }
}

function familyOf(tag: string): Family {
  const key = tag.trim().toLowerCase();
  const known = TAG_FAMILY.get(key);
  if (known) return known;

  let hash = 0;
  for (let i = 0; i < key.length; i++) {
    hash = (hash * 31 + key.charCodeAt(i)) % 100000;
  }
  return FAMILIES[hash % FAMILIES.length];
}

export function tagColor(tag: string): string {
  return FAMILY_TINT[familyOf(tag)];
}

export function tagBar(tag: string): string {
  return FAMILY_BAR[familyOf(tag)];
}
